<a href="https://colab.research.google.com/github/Abhishek-Adari/Computer-Vision-Projects/blob/main/Intro_to_deep_learning_with_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd

NUMPY ARRAYS AND ARRAYS

In [4]:
#creates a 2-D list/Matrix with random numbers
#checks .dtype
np1 = np.random.rand(3, 4)
np1
np1.dtype

dtype('float64')

TENSORS


In [9]:
tensor_2d = torch.randn(3, 4)
tensor_2d
tensor_2d.dtype

#Zeros method
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d
tensor_3d.dtype

torch.float32

In [12]:
##creating tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor.dtype
##is float64 because number was float32
##because numpy arrays have default of float 64

torch.float64

TENSOR OPERATIONS:RESHAPE

In [23]:
#Creates a tensor of range 10
my_torch = torch.arange(10)
my_torch
#my_torch.dtype

#changing orientation of tensor without changing the underlying data
my_torch = my_torch.reshape(5, 2)
my_torch = my_torch.reshape(2, -1)#if you're not sure about the data
my_torch

my_torch3 = torch.arange(100)
my_torch3.reshape(10, -1)

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

TENSOR OPERATION: VIEW

In [26]:
my_torch3.reshape(20,-1)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79],
        [80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]])

In [56]:
#assigning values to tensors
my_torch3[0] = 1000
my_torch3[1] = 1
my_torch3
# Grabbing Slices(Starts after the left and ends on the right)
my_torch3[1:]

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
        37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
        73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99])