<a href="https://colab.research.google.com/github/Abhishek-Adari/Computer-Vision-Projects/blob/main/part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [11]:
tensor_a = torch.arange(5)
tensor_b = torch.arange(4, 9)
tensor_b

tensor([4, 5, 6, 7, 8])

ADDITION OF TENSORS: Adding two tensors can be done only if they are the same size

In [17]:
tensor_a + tensor_b
#can also broadcast
tensor_c = torch.tensor([[1,1,1,1,1],[2,2,2,2, 2]])
tensor_c + tensor_a

tensor([[1, 2, 3, 4, 5],
        [2, 3, 4, 5, 6]])

TENSOR Subtraction: Subtracting is the exact same thing with the exact same syntax(can also use 'torch.sub()')

TENSOR Multiplication: Same as the above(can use torch.mul(tensors))

Tensor Division: Divides tensor are same as above (except changes the result tensor to dtype = float)

Tensor Modulus: Same and can use torch.mod()

Power: Exact same and can use torch.pow()


In [18]:
tensor_b


tensor([4, 5, 6, 7, 8])

In [21]:
tensor_b **= tensor_a
tensor_b

tensor([    1,     7,   100,  2197, 65536])